name: build
on:
  pull_request: {}
  workflow_dispatch: {}
env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      self_mutation_happened: ${{ steps.self_mutation.outputs.self_mutation_happened }}
    env:
      CI: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install dependencies
        run: yarn install --check-files --frozen-lockfile
      - name: Synth Project
        run: npx projen
      - name: Build
        run: yarn build
      - name: Debug:Sharp:Tar
        working-directory: packages/cdk-graph-plugin-diagram
        run: tar -ztvf ./dist/js/cdk-graph-plugin-diagram@0.0.0.jsii.tgz -v --wildcards 'package/node_modules/sharp/*'
      - name: Debug:Sharp:Tree:Pkg
        working-directory: packages/cdk-graph-plugin-diagram/node_modules/sharp
        run: tree
      - name: Debug:Sharp:Tree:Root
        working-directory: node_modules/sharp
        run: tree
      - name: Check for mutations
        run: git diff --ignore-space-at-eol --exit-code
